name       : openfortivpn
version    : 1.9.0
release    : 7
source     :
    - https://github.com/adrienverge/openfortivpn/archive/v1.9.0.tar.gz : 2087e9b6d785037d1eb0cf28c889612b7774dd3bf7652da15a43fc33068581d9
license    :
    - GPL-3.0-or-later
    - OpenSSL
component  : network.util
summary    : openfortivpn is a client for PPP+SSL VPN tunnel services.
description: |
    openfortivpn is a client for PPP+SSL VPN tunnel services. It spawns a pppd process and operates the communication between the gateway and this process. It is compatible with Fortinet VPNs.
rundeps    :
    - ppp
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
