name       : openfortivpn
version    : 1.4.0
release    : 1
source     :
    - https://github.com/adrienverge/openfortivpn/archive/v1.4.0.tar.gz : 3b5ddbf4c0aecc85e9630bb45e012f7e0b0db5a10276f03f8af55326db97d9b4
license    : 
    - GPL-3.0
    -  OpenSSL
component  : network.util 
summary    : openfortivpn is a client for PPP+SSL VPN tunnel services.
description: |
        openfortivpn is a client for PPP+SSL VPN tunnel services. It spawns a pppd process and operates the communication between the gateway and this process. It is compatible with Fortinet VPNs.
rundeps :
    - ppp
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
