name       : openfortivpn
version    : 1.6.0
release    : 4
source     :
    - https://github.com/adrienverge/openfortivpn/archive/v1.6.0.tar.gz : 205ab5ac512cbeee3c7a6f693518420ae66d6414c1d27247d002167e1906d6d3
license    :
    - GPL-3.0
    - OpenSSL
component  : network.util
summary    : openfortivpn is a client for PPP+SSL VPN tunnel services.
description: |
    openfortivpn is a client for PPP+SSL VPN tunnel services. It spawns a pppd process and operates the communication between the gateway and this process. It is compatible with Fortinet VPNs.
rundeps    :
    - ppp
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
