name       : openfortivpn
version    : 1.5.0
release    : 3
source     :
    - https://github.com/adrienverge/openfortivpn/archive/v1.5.0.tar.gz : a96016826bf85435c26ef0e58d14ae91990a08aaf67c701dfa56345dd851c185
license    :
    - GPL-3.0
    - OpenSSL
component  : network.util
summary    : openfortivpn is a client for PPP+SSL VPN tunnel services.
description: |
    openfortivpn is a client for PPP+SSL VPN tunnel services. It spawns a pppd process and operates the communication between the gateway and this process. It is compatible with Fortinet VPNs.
rundeps    :
    - ppp
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
