name       : openfortivpn
version    : 1.7.1
release    : 6
source     :
    - https://github.com/adrienverge/openfortivpn/archive/v1.7.1.tar.gz : 71222da680cdafbd48f648e4e1bc14822fa06eb84ab5e1fb58f28b6b4251baba
license    :
    - GPL-3.0-or-later
    - OpenSSL
component  : network.util
summary    : openfortivpn is a client for PPP+SSL VPN tunnel services.
description: |
    openfortivpn is a client for PPP+SSL VPN tunnel services. It spawns a pppd process and operates the communication between the gateway and this process. It is compatible with Fortinet VPNs.
rundeps    :
    - ppp
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
