name       : openfortivpn
version    : 1.7.0
release    : 5
source     :
    - https://github.com/adrienverge/openfortivpn/archive/v1.7.0.tar.gz : 1074e140c537c25f3da63501ebdb80671b770c5078e97aa9970b79d520009541
license    :
    - GPL-3.0-only
    - OpenSSL
component  : network.util
summary    : openfortivpn is a client for PPP+SSL VPN tunnel services.
description: |
    openfortivpn is a client for PPP+SSL VPN tunnel services. It spawns a pppd process and operates the communication between the gateway and this process. It is compatible with Fortinet VPNs.
rundeps    :
    - ppp
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
